<?php
$this->headTitle($this->translate('Sign-in'));
$this->headScript()->appendFile($this->asset('sign-in.js')->distribution()->get());
?>

<div id="kebab-system-backend-signIn-container" class="kebab-container kebab-rounded-corners kebab-shadow">

    <div id="signIn-form-wrapper">
        
        <h1 class="kebab-heading"><?php echo $this->translate('Sign-in'); ?></h1>

        <div id="signIn-form"></div>

    </div>

    <div id="forgotPassword-form-wrapper">

        <h1 class="kebab-heading"><?php echo $this->translate('Forgot password'); ?></h1>

        <div id="forgotPassword-form"></div>

    </div>

    <?php echo $this->render('backend/_progress-bar.phtml'); ?>

</div>