<?php
$this->headTitle('Sign-in');

$this->headLink()
      ->prependStylesheet($this->asset('login.css')->distribution()->theme()->get());

$this->headScript()
     ->appendFile($this->asset('login.js')->distribution()->get());
?>

<div id="kebab-system-backend-login-container" class="kebab-standart-container kebab-rounded-corners kebab-shadow">

    <div id="login-form-wrapper">
        
        <h1>Sign-in</h1>

        <div id="login-form"></div>

    </div>

    <div id="forgotPassword-form-wrapper">

        <h1>Forgot password</h1>

        <div id="forgotPassword-form"></div>

    </div>

    <div id="loader">
        <h2>Please wait...</h2>
        <a href="backend">Try again</a>
    </div>

</div>