<html>
<head>
<title>Welcome to the Kebab Framework</title>
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />

<style>
 body {
 background-color: #fff;
 margin: 40px;
 font-family: Lucida Grande, Verdana, Sans-serif;
 font-size: 14px;
 color: #4F5155;
}

a {
 color: #003399;
 background-color: transparent;
 font-weight: normal;
}

h1 {
 color: #444;
 background-color: transparent;
 border-bottom: 1px solid #D0D0D0;
 font-size: 16px;
 font-weight: bold;
 margin: 24px 0 2px 0;
 padding: 5px 0 6px 0;
}
</style>
<h1>Welcome to the <strong>Kebab Framework Reloaded</strong></h1>

<h2>My Account</h2>
<?php if ($this->identity == null) { ?>
    <p><a href="http://localhost/lab2023/kebab-reloaded/public/default/auth/login"> To login</a></p>
<?php } else { ?>
    <p>Welcome back <?php echo $this->identity->role; ?></p>
    <p><a href="http://localhost/lab2023/kebab-reloaded/public/default/auth/logout"> To logout </a></p>
<?php } ?>
</body>
</html>
