<?php

/**
 * SuperDuper_Model_SomeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SuperDuper_Model_SomeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SuperDuper_Model_SomeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SuperDuper_Model_Some');
    }
}