<?php

/**
 * System_Model_Base_Action
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $resource_id
 * @property string $action
 * @property System_Model_Resource $Resource
 * @property Doctrine_Collection $RoleAccess
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class System_Model_Base_Action extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('action');
        $this->hasColumn('resource_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('action', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('System_Model_Resource as Resource', array(
             'local' => 'resource_id',
             'foreign' => 'id'));

        $this->hasMany('System_Model_RoleAccess as RoleAccess', array(
             'local' => 'id',
             'foreign' => 'action_id'));
    }
}