<?php

/**
 * System_Model_Base_Module
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $moduleId
 * @property string $moduleName
 * @property Doctrine_Collection $Resources
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class System_Model_Base_Module extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('module');
        $this->hasColumn('moduleId', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('moduleName', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('System_Model_Resource as Resources', array(
             'local' => 'moduleId',
             'foreign' => 'moduleId'));
    }
}