<?php

/**
 * System_Model_Base_Resource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $resourceId
 * @property integer $moduleId
 * @property string $controller
 * @property System_Model_Module $Module
 * @property Doctrine_Collection $Actions
 * @property Doctrine_Collection $RoleAccess
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class System_Model_Base_Resource extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('resource');
        $this->hasColumn('resourceId', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('moduleId', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('controller', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('System_Model_Module as Module', array(
             'local' => 'moduleId',
             'foreign' => 'moduleId'));

        $this->hasMany('System_Model_Action as Actions', array(
             'local' => 'resourceId',
             'foreign' => 'resourceId'));

        $this->hasMany('System_Model_RoleAccess as RoleAccess', array(
             'local' => 'resourceId',
             'foreign' => 'resourceId'));
    }
}