<?php

/**
 * System_Model_Base_RoleAccess
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $roleId
 * @property integer $resourceId
 * @property integer $actionId
 * @property enum $allow
 * @property integer $assertionId
 * @property System_Model_Role $Role
 * @property System_Model_Resource $Resource
 * @property System_Model_Action $Action
 * @property System_Model_Assertion $Assertion
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class System_Model_Base_RoleAccess extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('role_access');
        $this->hasColumn('roleId', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('resourceId', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('actionId', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('allow', 'enum', 5, array(
             'type' => 'enum',
             'length' => 5,
             'values' => 
             array(
              0 => 'deny',
              1 => 'allow',
             ),
             ));
        $this->hasColumn('assertionId', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('System_Model_Role as Role', array(
             'local' => 'roleId',
             'foreign' => 'roleId'));

        $this->hasOne('System_Model_Resource as Resource', array(
             'local' => 'resourceId',
             'foreign' => 'resourceId'));

        $this->hasOne('System_Model_Action as Action', array(
             'local' => 'actionId',
             'foreign' => 'actionId'));

        $this->hasOne('System_Model_Assertion as Assertion', array(
             'local' => 'assertionId',
             'foreign' => 'assertionId'));
    }
}