<?php
$this->headTitle('Welcome Screen');
?>
    <div class="kebab-standart-container kebab-rounded-corners kebab-shadow kebab-opacity">
        
        <h1 class="kebab-heading">Welcome to the Kebab Project Reloaded</h1>

        <p class="kebab-paragraph">Congratulations! This is your project's main page.</p>

        <br />
        <p class="kebab-paragraph">Please <a href="<?php echo $this->baseUrl('auth')?>">login</a> this application</p>
        <p class="kebab-paragraph">Did you <a href="<?php echo $this->baseUrl('auth/forgot-password')?>">forget your password</a>?</p>
    </div>