<?php

/**
 * Model_Base_ApplicationAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $application_id
 * @property integer $asset_id
 * @property Model_Application $Application
 * @property Model_Asset $Asset
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_ApplicationAsset extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('application_asset');
        $this->hasColumn('application_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('asset_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Application as Application', array(
             'local' => 'application_id',
             'foreign' => 'id'));

        $this->hasOne('Model_Asset as Asset', array(
             'local' => 'asset_id',
             'foreign' => 'id'));
    }
}