<?php

/**
 * Model_Base_Asset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $description
 * @property string $path
 * @property enum $extension
 * @property Doctrine_Collection $Applications
 * @property Doctrine_Collection $ApplicationAsset
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Asset extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('asset');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('extension', 'enum', 4, array(
             'type' => 'enum',
             'length' => 4,
             'values' => 
             array(
              0 => 'css',
              1 => 'js',
             ),
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_Application as Applications', array(
             'refClass' => 'Model_ApplicationAsset',
             'local' => 'asset_id',
             'foreign' => 'application_id'));

        $this->hasMany('Model_ApplicationAsset as ApplicationAsset', array(
             'local' => 'id',
             'foreign' => 'asset_id'));
    }
}