<?php

/**
 * Model_Base_Permission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $role_id
 * @property integer $controller_id
 * @property integer $action_id
 * @property enum $rule
 * @property integer $assertion_id
 * @property Model_Role $Role
 * @property Model_Controller $Controller
 * @property Model_Action $Action
 * @property Model_Assertion $Assertion
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Permission extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('permission');
        $this->hasColumn('role_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('controller_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('action_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rule', 'enum', 5, array(
             'type' => 'enum',
             'length' => 5,
             'values' => 
             array(
              0 => 'deny',
              1 => 'allow',
             ),
             ));
        $this->hasColumn('assertion_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Role as Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));

        $this->hasOne('Model_Controller as Controller', array(
             'local' => 'controller_id',
             'foreign' => 'id'));

        $this->hasOne('Model_Action as Action', array(
             'local' => 'action_id',
             'foreign' => 'id'));

        $this->hasOne('Model_Assertion as Assertion', array(
             'local' => 'assertion_id',
             'foreign' => 'id'));
    }
}