<?php

/**
 * Model_Base_Resource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $controller_id
 * @property integer $action_id
 * @property Model_Controller $Controller
 * @property Model_Action $Action
 * @property Doctrine_Collection $Stories
 * @property Doctrine_Collection $StoryResource
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Resource extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('resource');
        $this->hasColumn('controller_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('action_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Controller as Controller', array(
             'local' => 'controller_id',
             'foreign' => 'id'));

        $this->hasOne('Model_Action as Action', array(
             'local' => 'action_id',
             'foreign' => 'id'));

        $this->hasMany('Model_Story as Stories', array(
             'refClass' => 'Model_StoryResource',
             'local' => 'resource_id',
             'foreign' => 'story_id'));

        $this->hasMany('Model_StoryResource as StoryResource', array(
             'local' => 'id',
             'foreign' => 'resource_id'));
    }
}