<?php

/**
 * Model_Base_Story
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $title
 * @property clob $description
 * @property Doctrine_Collection $Resources
 * @property Doctrine_Collection $Guis
 * @property Doctrine_Collection $StoryGui
 * @property Doctrine_Collection $Permission
 * @property Doctrine_Collection $StoryResource
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Story extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('story');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_Resource as Resources', array(
             'refClass' => 'Model_StoryResource',
             'local' => 'story_id',
             'foreign' => 'resource_id'));

        $this->hasMany('Model_Gui as Guis', array(
             'refClass' => 'Model_StoryGui',
             'local' => 'story_id',
             'foreign' => 'gui_id'));

        $this->hasMany('Model_StoryGui as StoryGui', array(
             'local' => 'id',
             'foreign' => 'story_id'));

        $this->hasMany('Model_Permission as Permission', array(
             'local' => 'id',
             'foreign' => 'story_id'));

        $this->hasMany('Model_StoryResource as StoryResource', array(
             'local' => 'id',
             'foreign' => 'story_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'description',
             ),
             'className' => 'StoryTranslation',
             'length' => 4,
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($i18n0);
        $this->actAs($softdelete0);
    }
}