<?php

/**
 * SysAdministration_Model_UsersAndGroupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SysAdministration_Model_UsersAndGroupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SysAdministration_Model_UsersAndGroupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SysAdministration_Model_UsersAndGroups');
    }
}