<div class="kebab-standart-container kebab-rounded-corners kebab-shadow kebab-opacity">
    <h1><strong>Kebab Framework Reloaded :: Accept Invitation</strong></h1>

    <form method="post" action="<?php echo $this->baseUrl('auth/accept-invitation/check/' . $this->activationKey); ?>">
        <strong>Username</strong>
        <input type="text" size="20" name="userName"><br />
        <strong>Password</strong>
        <input type="password" size="20" name="password"><br />
        <strong>Re-type Password</strong>
        <input type="password" size="20" name="re_password"><br />
        <input type="submit" value="Accept">
        or <a href="<?php echo $this->baseUrl('index'); ?>">Go back</a>
    </form>
</div>