<div class="kebab-standart-container kebab-rounded-corners kebab-shadow kebab-opacity">
    
    <h1 class="kebab-heading">Forgot Password Page</h1>

    <form method="post" action="<?php echo $this->baseUrl('auth/reset-password'); ?>">
        <strong>Password</strong>
        <input type="password" size="20" name="password"><br />
        <strong>Password Confirm</strong>
        <input type="password" size="20" name="password-confirm"><br />
        <input type="hidden" name="activation-key" value="<?php echo $this->activationKey; ?>">
        <input type="submit" name="password-resets" value="Reset Password">
        or <a href="<?php echo $this->baseUrl('index'); ?>">Go back</a>
    </form>
    
</div>