<?php
$this->headTitle('Unauthorized Access');
?>

<div id="kebab-system-auth-container" class="kebab-standart-container kebab-rounded-corners kebab-shadow kebab-opacity">

    <h1 class="kebab-heading">Unauthorized Access</h1>

    <p class="kebab-paragraph">You are not authorized to access this area.</p>

    <br />
    <p class="kebab-paragraph">Please <a href="<?php echo $this->baseUrl('auth')?>">login</a> this application</p>
    <p class="kebab-paragraph">Did you <a href="<?php echo $this->baseUrl('auth/forgot-password')?>">forget your password</a>?</p>
    
</div>