<?php

/**
 * SysPreferences_Model_Base_AboutMe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $aboutId
 * @property string $name
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class SysPreferences_Model_Base_AboutMe extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('about_me');
        $this->hasColumn('aboutId', 'integer', null, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}