<?php
$this->headTitle('Welcome Screen');
?>
    <div class="kebab-standart-container kebab-rounded-corners kebab-shadow kebab-opacity">
        <h1>Welcome to the Kebab Framework Reloaded</h1>

        <p>Congratulations! This is your project's main page.</p>

        <p>Please <a href="<?php echo $this->baseUrl('auth/index')?>">login</a> this application</p>
        <p>Are you <a href="<?php echo $this->baseUrl('auth/forgot-password')?>">forgot password</a>?</p>
    </div>