<?php
/**
 * Simple Kebab Developer Console & Profiling & Benchmarking Area
 */
$scriptTime         = number_format((microtime(true) - PROFILER_SCRIPT_START_TIME), 5,'.',',');
$mgpu               = number_format(memory_get_peak_usage(true));
$consolePosition    = Zend_Registry::get('config')->kebab->developerTools->position;
?>
<div id="kebab-developer-tools" class="kebab-developer-tools-<?php echo $consolePosition; ?>"
     title="Kebab Framework Developer Tools v.0.1">

    <?php if ($consolePosition == "top"): ?>
        <?php echo $this->render('sections/kebab-dev-tools/console.phtml'); ?>
    <?php endif; ?>
    
    <div id="kebab-developer-tools-img"></div>
    <p>
        <strong>Page render time :</strong>
        <span <?php echo $scriptTime > .2 ? 'style="color:red;"' : null ;?>>
            <?php echo $scriptTime; ?> seconds
        </span>
        <strong>&nbsp;&nbsp;·&nbsp;&nbsp;</strong>
        <strong>Memory peak usage :</strong>
        <span>
            <?php echo $mgpu; ?> bytes
        </span>
        <strong>&nbsp;&nbsp;·&nbsp;&nbsp;</strong>
        <strong>Application environment: </strong>
        <span class="env-<?php echo APPLICATION_ENV ?>"><?php echo APPLICATION_ENV; ?></span>
    </p>
    <em title="Kebab Framework Developer Tools v.0.1">Kebab Developer Tools v.0.1</em>

    <?php if ($consolePosition == "bottom"): ?>
        <?php echo $this->render('sections/kebab-dev-tools/console.phtml'); ?>
    <?php endif; ?>
    
</div>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/kebab/dev-tools/javascripts/dev-tools.js'); ?>"></script>