Module::SysAdministration > Controller::User > Action::sendInvitation

<h2>Invite User</h2>

<form method="post" action="<?php echo $this->baseUrl('sys-administration/user/send-invitation'); ?>">
    <label>First Name : </label> <input id="first_name" name="first_name"><br>
    <label>Surname : </label> <input id="surname" name="surname"><br>
    <label>E-mail : </label> <input id="email" name="email"><br>
    <label> Message (optional) </label> <textarea id="message" name="message"> </textarea>
    <input value="Send" type="submit" id="sendInvitation" name="sendInvitation" title="Send Invitation">
</form>
