<?php

/**
 * SysPreferences_Model_AboutMeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SysPreferences_Model_AboutMeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SysPreferences_Model_AboutMeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SysPreferences_Model_AboutMe');
    }
}