<?php

/**
 * SysPreferences_Model_AboutMe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SysPreferences_Model_AboutMe extends SysPreferences_Model_Base_AboutMe
{

}