<?php
$this->headTitle('Main page');
?>
<div class="kebab-standart-container kebab-rounded-corners kebab-shadow">
    <h1>Main page</h1>

    <?php if ($this->identity == null): ?>

        <p><a href="<?php echo $this->baseUrl('auth'); ?>"> To login</a></p>

    <?php else: ?>

        <p>Welcome back <?php echo $this->identity->username; ?></p>

        <h4>Roles</h4>
        <p><?php Zend_Debug::dump($this->identity->roles); ?></p>

        <p><a href="<?php echo $this->baseUrl('auth/logout'); ?>"> To logout </a></p>

    <?php endif; ?>
</div>
