    <h1><strong>Kebab Framework Reloaded :: Account Page</strong></h1>
    
    <?php if ($this->identity == null): ?>

        <p><a href="<?php echo $this->baseUrl('auth/index'); ?>"> To login</a></p>

    <?php else: ?>

        <p>Welcome back <?php echo $this->identity->userName; ?></p>

        <h4>Roles</h4>
        <p><?php Zend_Debug::dump($this->identity->roles); ?></p>

        <p><a href="<?php echo $this->baseUrl('auth/logout'); ?>"> To logout </a></p>

    <?php endif; ?>
