<html>
<head>
<title>Welcome to the Kebab Framework</title>

<style>
 body {
 background-color: #fff;
 margin: 40px;
 font-family: Lucida Grande, Verdana, Sans-serif;
 font-size: 14px;
 color: #4F5155;
}

a {
 color: #003399;
 background-color: transparent;
 font-weight: normal;
}

h1 {
 color: #444;
 background-color: transparent;
 border-bottom: 1px solid #D0D0D0;
 font-size: 16px;
 font-weight: bold;
 margin: 24px 0 2px 0;
 padding: 5px 0 6px 0;
}
</style>
<h1>Welcome to the <strong>Kebab Framework</strong></h1>

<p>Congratulations! This is your project's main page.</p>

<p>
    <a href="http://www.kebab.tc/" target="_blank">Kebab Framework website</a> |
    <a href="http://www.kebab.tc/?page_id=26" target="_blank">About this framework</a>
</p>

</body>
</html>
