<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Welcome to the Kebab Framework</title>
    <?php
    echo $this->headLink()
        ->appendStylesheet($this->baseUrl('assets/kebab/system/stylesheets/layout.css'))
        ->appendStylesheet($this->baseUrl('assets/kebab/dev-tools/stylesheets/dev-tools.css'));
    ?>
    <link rel="shortcut icon" href="<?php echo $this->baseUrl('favicon.ico'); ?>" type="image/x-icon" />
</head>
<body>

    <?php echo $this->layout()->content; ?>

    <p>
        <a href="http://www.kebab-project.com" title="Kebab Framework Website"  target="_blank">www.kebab-project.com</a>
    </p>
</body>
</html>
<?php if (Zend_Registry::get('config')->kebab->developerTools->enable): ?>
    <?php echo $this->render('sections/kebab-dev-tools/body.phtml'); ?>
<?php endif; ?>