<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Welcome to the Kebab Framework</title>
    <?php 
        echo $this->headLink()
                ->appendStylesheet('/assets/stylesheets/layout.css');
    ?>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
</head>
<body>

    <?php echo $this->layout()->content; ?>

    <p>
        <a href="http://www.kebab-project.com" title="Kebab Framework Website"  target="_blank">www.kebab-project.com</a>
    </p>
</body>
</html>