<?php

/**
 * Model_Entity_Action
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $controller_id
 * @property string $name
 * @property Model_Entity_Controller $Controller
 * @property Doctrine_Collection $Service
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Entity_Action extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('system_action');
        $this->hasColumn('controller_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Entity_Controller as Controller', array(
             'local' => 'controller_id',
             'foreign' => 'id'));

        $this->hasMany('Model_Entity_Service as Service', array(
             'local' => 'id',
             'foreign' => 'action_id'));
    }
}