<?php

/**
 * Model_Entity_Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $description
 * @property string $iconCls
 * @property integer $image_id
 * @property Model_Entity_Media $Image
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Entity_Category extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('system_category');
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('iconCls', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('image_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Entity_Media as Image', array(
             'local' => 'image_id',
             'foreign' => 'id'));
    }
}