<?php

/**
 * Model_Entity_Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $description
 * @property string $iconCls
 * @property integer $image_id
 * @property Model_Entity_Media $Image
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Entity_Category extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('system_category');
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('iconCls', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('image_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Entity_Media as Image', array(
             'local' => 'image_id',
             'foreign' => 'id'));

        $blameable0 = new Doctrine_Template_Blameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             'rootColumnName' => 'root_id',
             ));
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'description',
             ),
             'className' => 'SystemCategoryTranslation',
             'length' => 2,
             ));
        $searchable1 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'description',
             ),
             'className' => 'SystemCategorySearch',
             ));
        $i18n0->addChild($searchable1);
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($blameable0);
        $this->actAs($timestampable0);
        $this->actAs($nestedset0);
        $this->actAs($i18n0);
    }
}