<?php

/**
 * Model_Entity_Invitation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $activationKey
 * @property text $message
 * @property Model_Entity_User $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Entity_Invitation extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('system_invitation');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('activationKey', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('message', 'text', null, array(
             'type' => 'text',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Entity_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'cascade' => array(
             0 => 'delete',
             )));

        $blameable0 = new Doctrine_Template_Blameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($blameable0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}