<?php

/**
 * Model_Entity_Permission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $role_id
 * @property integer $story_id
 * @property enum $rule
 * @property Model_Entity_Role $Role
 * @property Model_Entity_Story $Story
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Entity_Permission extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('system_permission');
        $this->hasColumn('role_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('story_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('rule', 'enum', 5, array(
             'type' => 'enum',
             'length' => 5,
             'values' => 
             array(
              0 => 'deny',
              1 => 'allow',
             ),
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Entity_Role as Role', array(
             'local' => 'role_id',
             'foreign' => 'id'));

        $this->hasOne('Model_Entity_Story as Story', array(
             'local' => 'story_id',
             'foreign' => 'id'));
    }
}