<?php

/**
 * Model_Entity_Service
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $story_id
 * @property integer $controller_id
 * @property integer $action_id
 * @property Model_Entity_Story $Story
 * @property Model_Entity_Controller $Resource
 * @property Model_Entity_Action $Action
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     lab2023 - Dev. Team <info@lab2023.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Entity_Service extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('system_service');
        $this->hasColumn('story_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('controller_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('action_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_bin');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Entity_Story as Story', array(
             'local' => 'story_id',
             'foreign' => 'id'));

        $this->hasOne('Model_Entity_Controller as Resource', array(
             'local' => 'controller_id',
             'foreign' => 'id'));

        $this->hasOne('Model_Entity_Action as Action', array(
             'local' => 'action_id',
             'foreign' => 'id'));
    }
}