<?php $this->headTitle('Yetkisiz Erişim'); ?>

<div id="kebab-system-auth-container" class="kebab-standart-container kebab-rounded-corners kebab-shadow kebab-opacity">

    <h1 class="kebab-heading">Yetkisiz Erişim</h1>

    <p class="kebab-paragraph">Bu alanı görmeye yetkiniz bulunmamaktadır.</p>

    <br />
    <p class="kebab-paragraph">Lütfen sisteme <a href="<?php echo $this->baseUrl('auth')?>">oturum açınız.</a></p>
    <p class="kebab-paragraph"><a href="<?php echo $this->baseUrl('auth/forgot-password')?>">Şifrenizi mi unuttunuz ?</a></p>
    
</div>