<?php
$this->headTitle($this->translate('Unauthorized Access')); ?>

<div id="kebab-system-auth-container" class="kebab-standart-container kebab-rounded-corners kebab-shadow kebab-opacity">

    <h1 class="kebab-heading"><?php echo $this->translate('Unauthorized Access'); ?></h1>

    <p class="kebab-paragraph"><?php echo $this->translate('You are not authorized to see this field.'); ?></p>

    <br />
    <p class="kebab-paragraph"><?php echo $this->translate('Please'); ?> <a href="<?php echo $this->baseUrl('auth')?>"><?php $this->translate('Sign in'); ?></a></p>
    <p class="kebab-paragraph"><a href="<?php echo $this->baseUrl('auth/forgot-password')?>"><?php echo $this->translate('Did Forgot your password?'); ?></a></p>
    
</div>