<?php
$this->headTitle('Desktop');

$this->headLink()
     ->appendStylesheet($this->asset('desktop.css')->distribution()->theme()->get());
$this->headScript()
     ->appendFile($this->asset('kernel/Kernel.js')->distribution()->get())
     ->appendFile($this->asset('kernel/Application.js')->distribution()->get())
     ->appendFile($this->asset('kernel/Desktop.js')->distribution()->get())
     ->appendFile($this->asset('kernel/Panel.js')->distribution()->get())
     ->appendFile($this->asset('kernel/Notification.js')->distribution()->get())
     ->appendFile($this->asset('kernel/Extras.js')->distribution()->get());
?>

    <?php 
    // BEGIN: Kernel Boot & All Applications Load ------------------------------
    foreach ($this->applications as $application) {
        
        // TODO Load on-demand
        $this->headLink()->appendStylesheet(
                
                
            $this->assetApplication($application['name'] .'/web/assets/style.css')
                 ->department($application['department'])
                 ->get()
        );
        
        $this->headScript()->appendFile(
            $this->assetApplication($application['name'])
             ->department($application['department'])
             ->version($application['version'])
             ->get()
        );
    }
    ?>
    <script type="text/javascript">
    Ext.namespace('KebabOS', 'KebabOS.kernel');
    KebabOS.kernel = new Kebab.OS.Kernel({

        distribution    : '<?php echo $this->variable('kebabOs')->distributions->current; ?>',
        
        environment     : '<?php echo APPLICATION_ENV; ?>',
        
        user            : '<?php echo json_encode($this->user); ?>',
        
        apps            : '<?php echo json_encode($this->applications); ?>',

        getApplications : function(){
            return [
                new KebabOS.applications.preferences.AboutMe() // Convert to JSON object
            ];
        }
    });
    </script>
    <?php // END: Kernel Boot & All Applications Load ------------------------?>

    <?php // BEGIN: OS Panel -------------------------------------------------?>
    <div id="kebab-os-panel" class="kebab-shadow-std"> 
        <div id="kebab-os-panel-main-menu"></div> 
        <div id="kebab-os-panel-window-list"></div>
        <div id="kebab-os-panel-indicators"></div>
        <div class="kebab-os-panel-clear"></div> 
    </div>
    <?php // END: OS Panel ---------------------------------------------------?>

    <?php // BEGIN: OS Desktop Environment -----------------------------------?>
    <div id="kebab-os-desktop"> 
        
        <?php foreach ($this->applications as $application): // TODO Move to DOM ?>
        <dl id="kebab-os-desktop-shortcuts"> 
            <dt ext:qtip="<?php echo $application['name']; ?>" id="<?php echo $application['identity']; ?>-shortcut">
                <span><?php echo $application['name']; ?></span>
            </dt>       
        </dl>
        <?php endforeach; ?>
        
    </div>
    <?php // END: OS Desktop Environment -------------------------------------?>