<?php
$this->headTitle('Desktop');

$this->headLink()
     ->appendStylesheet($this->asset('desktop.css')->distribution()->theme()->get());

$this->headScript()
     ->appendFile($this->asset('kernel')->distribution()->get())
     ->appendFile($this->asset('kernel/Application.js')->distribution()->get())
     ->appendFile($this->asset('kernel/Desktop.js')->distribution()->get())
     ->appendFile($this->asset('kernel/Panel.js')->distribution()->get())
     ->appendFile($this->asset('kernel/Notification.js')->distribution()->get())             
     ->appendFile($this->asset('kernel/Translator.js')->distribution()->get())
     ->appendFile($this->asset('kernel/Logger.js')->distribution()->get())
     ->appendFile($this->asset('kernel/Extras.js')->distribution()->get());
?>

    <?php 
    // BEGIN: Kernel Boot & All Applications Load ------------------------------
    foreach ($this->applications as $application) {
        
        // TODO Load on-demand
        $this->headLink()->appendStylesheet(
            $this->assetApplication($application['name'] .'/web/theme/style.css')
                 ->department($application['department'])
                 ->get(),
            'screen', true, array('id' => $application['identity'] . '-style')
        );
        
        $this->headScript()->appendFile(
            $this->assetApplication($application['name'])
             ->department($application['department'])
             ->version($application['version'])
             ->get()
        );
    }
    ?>
    <script type="text/javascript">
        
    var APPLICATION_ENV = "<?php echo APPLICATION_ENV; ?>";
    var BASE_URL = "<?php echo BASE_URL; ?>";
    
    Ext.namespace('KebabOS', 'KebabOS.kernel', 'KebabOS.applications');
    KebabOS.kernel = new Kebab.OS.Kernel({

        distribution    : "<?php echo $this->variable('kebabOs')->distributions->current; ?>",
        
        environment     : APPLICATION_ENV,
        
        baseUrl         : BASE_URL,
        
        languages       : <?php echo json_encode($this->languages); ?>,
        
        user            : <?php echo json_encode($this->user); ?>,

        apps            : <?php echo json_encode($this->applications); ?>
    });
    </script>
    <?php // END: Kernel Boot & All Applications Load ------------------------?>

    <?php // BEGIN: OS Panel -------------------------------------------------?>
    <div id="kebab-os-panel" class="kebab-shadow-std"> 
        <div id="kebab-os-panel-main-menu"></div> 
        <div id="kebab-os-panel-window-list"></div>
        <div id="kebab-os-panel-indicators"></div>
        <div class="kebab-os-panel-clear"></div> 
    </div>
    <?php // END: OS Panel ---------------------------------------------------?>

    <?php // BEGIN: OS Desktop Environment -----------------------------------?>
    <div id="kebab-os-desktop"> 
        <dl id="kebab-os-desktop-shortcuts">
            <?php foreach ($this->applications as $application): // TODO Move to DOM ?>
            <dt ext:qtip="<?php echo $application['name']; ?>" id="<?php echo $application['identity']; ?>-shortcut">
                <span><?php echo $application['name']; ?></span>
            </dt>
            <?php endforeach; ?>      
        </dl>
        
    </div>
    <?php // END: OS Desktop Environment -------------------------------------?>
