<?php

/**
 * Kernel_Model_UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Kernel_Model_UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Kernel_Model_UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Kernel_Model_User');
    }
}