<?php

/**
 * System_Model_ControllerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class System_Model_ControllerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object System_Model_ControllerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('System_Model_Controller');
    }
}