<?php

/**
 * System_Model_ModuleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class System_Model_ModuleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object System_Model_ModuleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('System_Model_Module');
    }
}