<div class="kebab-standart-container kebab-rounded-corners kebab-shadow">
    
    <h1 class="kebab-heading">Forgot Password</h1>

    <form method="post" action="<?php echo $this->baseUrl('auth/forgot-password'); ?>">
        <strong>Email</strong>
        <input type="input" size="20" name="email"><br />
        <input type="submit" value="Send Password">
        or <a href="<?php echo $this->baseUrl('index'); ?>">Go back</a>
    </form>
    
</div>