<html>
<head>
<title>Kebab Framework Reloaded :: Login Page</title>
<link rel="shortcut icon" href="<?php echo $this->baseUrl('favicon.ico')?>" type="image/x-icon" />

<style>
 body {
 background-color: #fff;
 margin: 40px;
 font-family: Lucida Grande, Verdana, Sans-serif;
 font-size: 14px;
 color: #4F5155;
}

a {
 color: #003399;
 background-color: transparent;
 font-weight: normal;
}

h1 {
 color: #444;
 background-color: transparent;
 border-bottom: 1px solid #D0D0D0;
 font-size: 16px;
 font-weight: bold;
 margin: 24px 0 2px 0;
 padding: 5px 0 6px 0;
}
</style>

<h1><strong>Kebab Framework Reloaded :: Login Page</strong></h1>

<form method="post" action="<?php echo $this->baseUrl('auth/login'); ?>">
    <strong>Username</strong>
    <input type="text" size="20" name="username"><br />
    <strong>Password</strong>
    <input type="password" size="20" name="password"><br />
    <input type="submit" name="login" value="Login"> or <a href="<?php echo $this->baseUrl('index'); ?>">Go back</a>
</form>

<p>
    <a href="http://www.kebab-project.com" title="Kebab Framework Website"  target="_blank">www.kebab-project.com</a>
</p>
</body>
</html>