    <h1><strong>Kebab Framework Reloaded :: Login Page</strong></h1>

    <form method="post" action="<?php echo $this->baseUrl('auth/login'); ?>">
        <strong>Username</strong>
        <input type="text" size="20" name="username"><br />
        <strong>Password</strong>
        <input type="password" size="20" name="password"><br />
        <input type="submit" name="login" value="Login"> or <a href="<?php echo $this->baseUrl('index'); ?>">Go back</a>
    </form>