<?php
$this->headTitle('Login Screen');
$this->headLink()->prependStylesheet(
    $this->kebabAsset('auth/stylesheets/auth.css')->theme($this->kebabVariable('kebabTheme'))->get()
);
?>

<div id="kebab-system-auth-container" class="kebab-centered-container kebab-rounded-corners kebab-shadow kebab-opacity">

    <div id="kebab-system-auth-logo">
        <img src="http://www.tayfunoziserikan.com/images/tayfun-ozis-erikan.jpg" alt="APP LOGO" />
    </div>
    
</div>