<div class="kebab-standart-container kebab-rounded-corners kebab-shadow">
    <h1><strong>Kebab Framework Reloaded :: Reset Password Page</strong></h1>

    <h2>This reset password page has expired</h2>

    <p>For security reasons, reset password pages stop working after you use them to reset a password.</p>
    <p>If you're trying to reset your password, please <a href="<?php echo $this->baseUrl('index'); ?>">go back to the login screen</a> and click the "forgot password" link to reset it again.</p>
</div>