<div class="kebab-standart-container kebab-rounded-corners kebab-shadow">

    <h1 class="kebab-heading">Reset Password Page</h1>

    <h2>This reset password page has expired</h2>

    <p class="kebab-paragraph">For security reasons, reset password pages stop working after you use them to reset a password.</p>
    <p class="kebab-paragraph">If you're trying to reset your password, please <a href="<?php echo $this->baseUrl('index'); ?>">go back to the login screen</a> and click the "forgot password" link to reset it again.</p>
    
</div>