    <h1><?php echo $this->translate('Reset your Kebab Project password'); ?></h1>

    <p><?php echo $this->translate('Hi'); ?></p>

    <p><?php echo $this->translate('Can\'t remember your password? Don\'t worry about it — it happens.'); ?></p>

    <strong><?php echo $this->translate('Your password'); ?> :</strong>
    <p><?php echo $this->password; ?></p>
    <hr />
    <p><?php echo $this->translate('Eat fish to improve your memory. :)'); ?></p>