    <h1>Reset your Kebab Framework password</h1>

    <p>Hi</p>

    <p>Can't remember your password? Don't worry about it — it happens.</p>

    <strong>Just click this link to reset your password:</strong>
    <p><a href="<?php echo $this->baseUrl(); ?>/auth/reset-password/activation-key/<?php echo $this->activationKey; ?>"><?php echo $this->baseUrl(); ?>/auth/reset-password/activation-key/<?php echo $this->activationKey; ?></a></p>

    <hr />
    <strong>Didn't ask to reset your password?</strong>
    <p>If you didn't ask for your password, it's likely that another user
        entered your username or email address by mistake while trying to
        reset their password. If that's the case, you don't need to take any
        further action and can safely disregard this email.</p>