<?php echo $this->doctype() . PHP_EOL; ?>
<html>
<head>    
    <?php // META AREA -------------------------------------------------------?>
    <meta charset="UTF-8" />
    <meta name="Author" content="lab2023 Dev. Team: http://www.lab2023.com/" />
    <meta name="Author-Corporate" content="lab2023 Dev. Team, 2010 - 2011, http://www.lab2023.com/" />
    <meta name="Copyright" content="lab2023 Dev. Team, 2010 - 2011, http://www.lab2023.com/" />
    <meta name="Framework" content="Kebab Project - www.kebab-project.com" />
    <meta http-equiv="Accept-encoding" content="gzip,deflate" />
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <?php echo $this->headMeta(); ?>

    <?php // TITLE AREA ------------------------------------------------------?>
    <?php echo $this->headTitle($this->translate('Kebab Project • Web Operation System'))->setSeparator(' • '); ?>

    <?php // LINK AREA -------------------------------------------------------?>
    <link href="<?php echo $this->assetVendor('resources/css/ext-all-notheme.css')->get('extjs', true); ?>" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->assetVendor('resources/css/xtheme-gray.css')->get('extjs', true); ?>" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->assetVendor('examples/ux/css/ux-all.css')->get('extjs', true); ?>" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->assetVendor('silk/famfamfam-silk-icons.css')->get('famfamfam', true); ?>" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->assetVendor('flags/famfamfam-flag-icons.css')->get('famfamfam', true); ?>" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->asset('kernel.css')->distribution()->theme()->get(); ?>" media="screen" rel="stylesheet" type="text/css" />
    <?php echo $this->headLink(array('rel' => 'favicon','href' => $this->asset('favicon.ico')->get(false))); ?>

    <?php // STYLE AREA ------------------------------------------------------?>
    <style type="text/css">
        body {background:<?php echo $this->variable('os')->distributions->background->color; ?> url('<?php echo $this->asset('wallpapers/'.$this->variable('os')->distributions->background->image)->get(); ?>') center;}
    </style>
    <?php echo $this->headStyle(); ?>
    
    <?php // SCRIPT AREA -----------------------------------------------------?>
    <script type="text/javascript">
    var APPLICATION_ENV = "<?php echo APPLICATION_ENV; ?>";
    var BASE_URL = "<?php echo BASE_URL; ?>";
    var LANGUAGES = <?php echo json_encode($this->language()); ?>;
    </script>

    <!--[if IE]>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
        <style type="text/css">.chromeFrameInstallDefaultStyle {width: 100%;}</style>
        <script type="text/javascript">window.attachEvent("onload", function() {CFInstall.check({mode: "overlay", node: "prompt"});});</script>
    <![endif]-->

    <?php
    echo $this->headScript()
        ->prependFile($this->asset('library')->get())
        ->prependFile($this->asset('languages/'.$this->translate()->getLocale().'.js')->distribution()->get())
        ->prependFile($this->asset('kernel/kernel-all.js')->distribution()->get())
        ->prependFile($this->assetVendor('src/locale/ext-lang-'.$this->translate()->getLocale().'.js')->get('extjs', true))
        ->prependFile($this->assetVendor('examples/ux/ux-all.js')->get('extjs'))
        ->prependFile($this->assetVendor('ext-all.js')->get('extjs'))
        ->prependFile($this->assetVendor('adapter/ext/ext-base.js')->get('extjs'));
    ?>
</head>
<body>

    <!--[if IE]><div id="prompt"></div><![endif]-->

    <!-- RIBBON & PAGE LOADER -->
    <div id="beta-ribbon"></div>
    <div id="kebab-loading-mask"></div>

    <?php echo $this->layout()->content . PHP_EOL; ?>

    <!-- PROJECT INFO BUBBLE -->
    <div id="project-info" class="kebab-rounded-corners kebab-shadow">
        <a href="<?php echo $this->settings('project')->url; ?>" target="_blank">
            <p><?php echo $this->settings('project')->info; ?></p>
            <p><strong>Version:</strong><br/><?php echo $this->settings('project')->version; ?></p>
            <p><strong>Release Date:</strong><br/><?php echo $this->settings('project')->releaseDate; ?></p>
        </a>
    </div>

</body>
</html>
