<?php echo $this->doctype() . PHP_EOL; ?>
<html>
<head>    
    <?php // META AREA -------------------------------------------------------?>
    <meta charset="UTF-8" />
    <meta name="Author" content="lab2023 Dev. Team: http://www.lab2023.com/" />
    <meta name="Author-Corporate" content="lab2023 Dev. Team, 2010 - 2011, http://www.lab2023.com/" />
    <meta name="Copyright" content="lab2023 Dev. Team, 2010 - 2011, http://www.lab2023.com/" />
    <meta name="Framework" content="Kebab Project - www.kebab-project.com" />
    <meta http-equiv="Accept-encoding" content="gzip,deflate" />
    <?php echo $this->headMeta(); ?>

    <?php // TITLE AREA ------------------------------------------------------?>
    <?php echo $this->headTitle('Kebab Project • Front-end')->setSeparator(' :: '); ?>

    <?php // LINK AREA -------------------------------------------------------?>
    <link href="<?php echo $this->assetVendor('resources/css/ext-all-notheme.css')->get('extjs', true); ?>" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->assetVendor('resources/css/xtheme-gray.css')->get('extjs', true); ?>" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->assetVendor('css/960-all.css')->get('960gs', true); ?>" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->assetVendor('silk/famfamfam-silk-icons.css')->get('famfamfam', true); ?>" media="screen" rel="stylesheet" type="text/css" />
    <?php
        echo $this->headLink(array('rel' => 'favicon','href' => $this->asset('favicon.ico')->getWeb()))
                ->prependStylesheet($this->asset('frontend/layout.css')->get(false));
    ?>
    
    <?php // STYLE AREA ------------------------------------------------------?>
    <?php echo $this->headStyle(); ?>
</head>
<body>

    <!-- RIBBOn & PAGE LOADER -->
    <div id="beta-ribbon"></div>
    
    <div id="wrapper" class="container_12">

        <div id="contents" class="container_12">
            <div class="grid_12"><?php echo $this->layout()->content . PHP_EOL; ?></div>
        </div>

        <div class="clear"></div>
    </div>


    <?php // SCRIPT AREA -----------------------------------------------------?>
    <?php echo $this->headScript();?>
</body>
</html>
