<?php echo $this->doctype() . PHP_EOL; ?>
<html>
<head>    
    <?php // META AREA -------------------------------------------------------?>
    <meta content="text/html; charset=UTF-8" />
    <meta name="Author" content="lab2023 Dev. Team: http://www.lab2023.com/" />
    <meta name="Author-Corporate" content="lab2023 Dev. Team, 2010 - 2011, http://www.lab2023.com/" />
    <meta name="Copyright" content="lab2023 Dev. Team, 2010 - 2011, http://www.lab2023.com/" />
    <meta http-equiv="Accept-encoding" content="gzip,deflate" />
    <?php echo $this->headMeta(); ?>

    <?php // TITLE AREA ------------------------------------------------------?>
    <?php echo $this->headTitle('Kebab Project')->setSeparator(' :: '); ?>

    <?php // LINK AREA -------------------------------------------------------?>
    <link href="<?php echo $this->asset('kernel.css')->distribution()->theme()->get(); ?>" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->assetVendor('resources/css/ext-all-notheme.css')->get('extjs', true); ?>" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->assetVendor('resources/css/xtheme-gray.css')->get('extjs', true); ?>" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->assetVendor('silk/famfamfam-silk-icons.css')->get('famfamfam', true); ?>" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->assetVendor('flags/famfamfam-flag-icons.css')->get('famfamfam', true); ?>" media="screen" rel="stylesheet" type="text/css" />
    <?php echo $this->headLink(); ?>

    <?php // STYLE AREA ------------------------------------------------------?>
    <?php echo $this->headStyle(); ?>
    <style>
    body {
        background:
            <?php echo $this->variable('kebabOs')->distributions->background->color; ?> 
            url('<?php echo $this->asset('wallpapers/'.$this->variable('kebabOs')->distributions->background->image)->get(); ?>')
            center;
    }
    </style>
    
    <?php // SCRIPT AREA -----------------------------------------------------?>
    <?php
    echo $this->headScript()
        ->prependFile($this->assetVendor('ext-all.js')->get('extjs', false))
        ->prependFile($this->assetVendor('adapter/ext/ext-base.js')->get('extjs', false));
    ?>
    
</head>
<body>
    
    <?php echo $this->layout()->content . PHP_EOL; ?>
    
</body>
</html>